refactor(deps): simplify run_as_root control flow

diff --git a/home/.chezmoiscripts/run_onchange_before_1-2.dependencies-apk.sh.tmpl b/home/.chezmoiscripts/run_onchange_before_1-2.dependencies-apk.sh.tmpl
--- a/home/.chezmoiscripts/run_onchange_before_1-2.dependencies-apk.sh.tmpl
+++ b/home/.chezmoiscripts/run_onchange_before_1-2.dependencies-apk.sh.tmpl
@@ -21,16 +21,12 @@ fi
 run_as_root() {
   if [ "$(id -u)" -eq 0 ]; then
     "$@"
-    return
-  fi
-
-  if command -v sudo >/dev/null; then
+  elif command -v sudo >/dev/null; then
     sudo "$@"
-    return
+  else
+    printf '>>> Error: %s\n' "sudo is required when not running as root"
+    exit 1
   fi
-
-  printf '>>> Error: %s\n' "sudo is required when not running as root"
-  exit 1
 }
 
 printf '>>> Installing... %s\n' "apk packages"
