feat: add support for apk package management in installation scripts
Signed-off-by: Kamontat Chantrachirathumrong <14089557+kamontat@users.noreply.github.com>

diff --git a/home/.chezmoiscripts/run_onchange_before_1.prerequisite-deps.sh.tmpl b/home/.chezmoiscripts/run_onchange_before_1.prerequisite-deps.sh.tmpl
--- a/home/.chezmoiscripts/run_onchange_before_1.prerequisite-deps.sh.tmpl
+++ b/home/.chezmoiscripts/run_onchange_before_1.prerequisite-deps.sh.tmpl
@@ -59,4 +59,13 @@ if ! command -v apt >/dev/null; then
   exit 1
 fi
 
+{{- end }}
+{{- if dig "apk" "packages" list . }}
+
+printf '>> Checking... %s\n' "apk"
+if ! command -v apk >/dev/null; then
+  echo 'Missing apk command' >&2
+  exit 1
+fi
+
 {{- end }}{{- end }}
