feat(chezmoi): add dependency scripts for new schema

diff --git a/home/.chezmoitemplates/shellVars/brew.tmpl b/home/.chezmoitemplates/shellVars/brew.tmpl
--- a/home/.chezmoitemplates/shellVars/brew.tmpl
+++ b/home/.chezmoitemplates/shellVars/brew.tmpl
@@ -3,3 +3,8 @@ brew_bin="${HOMEBREW_PREFIX:-}/bin"
 [ -f "$brew_bin/brew" ] || brew_bin="/usr/local/bin"                 ## default on macos (intel)
 [ -f "$brew_bin/brew" ] || brew_bin="/home/linuxbrew/.linuxbrew/bin" ## default on linux
 brew_cmd="$brew_bin/brew"
+
+if ! [ -x "$brew_cmd" ]; then
+  printf '>>> Error: %s\n' "brew command not found"
+  exit 1
+fi
